### ISSUE TITLE
Unable to build project due to `libspa` build errors

### ISSUE THREAD

**Issue by ViddeM** [YaLTeR/niri#367]
When I try to build the project, with or without the `--release` flag I get build errors from the libspa dependency (coming from the pipewire dep). 

I have tried using both using the stable rustc release (`1.78.0`) and nightly (`1.80.0`). 

Am I doing something wrong or has there been a breaking change somewhere?

### System Information

* niri version: I have tried building both the latest commit on main (14d637f4efb6053c7243930944861f9eaf6127d3) and the latest release tag (v0.1.6, d96a66ddff1a6b88dbe3e23b049f7075533b216f) with the same result.

* Distro: Ubuntu 24.04.4 LTS

* GPU: Nvidia A2000

* CPU: Intel i7-11850H

**Comment by YaLTeR** [comment]
Check that you have a recent enough libpipewire-0.3-dev

**Comment by ViddeM** [comment]
I was indeed using an older version of libpipewire, had to add their repository to get the new one.

However, even after updating from `0.3.48` to `1.0.3` the same compilation errors are still there but I see that on their gitlab the latest version seems to be `1.1.81` so I'm trying to figure out what the intended way of installing that on ubuntu is :sweat_smile:.

**Comment by ViddeM** [comment]
Nevermind I did a cargo clean and now it works. Now I got a linking error but it seems to be unrelated to this so I'll close this.

Thanks for the quick reply! 
I'm excited to try out what seems to be a really cool project! :)

**Comment by YaLTeR** [comment]
Alright, cool! The CI builds on Ubuntu 23.10 with pipewire from its repos, so it should be sufficient.
