### ISSUE TITLE
Build fails in lastest release

### ISSUE THREAD

**Issue by axtloss** [YaLTeR/niri#132]
Attempting to build niri, both from the main branch and the latest release fails with the error `private type `Msg` in public interface`

```
error[E0446]: private type `Msg` in public interface
  --> src/ipc/client.rs:11:1
   |
11 | pub fn handle_msg(msg: Msg, json: bool) -> anyhow::Result<()> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
   |
  ::: src/main.rs:89:1
   |
89 | enum Msg {
   | -------- `Msg` declared as private
```
### System Information

* niri version: -

* GPU: intel uhd + nvidia 3060 mobile

* CPU: intel i5-10300H

**Comment by axtloss** [comment]
Removing my existing `~/.cargo` and using cargo from the arch repositories resolves this issue, not sure if it has something to do with the code or my cargo setup

**Comment by raininja** [comment]
I have the exact same error on build, removing ~/.cargo/ did not alleviate the problem for me. 

### System info

```
CPU: 8-core AMD Ryzen 9 4900HS with Radeon Graphics (-MT MCP-)
speed/min/max: 1655/1400/3000 MHz Kernel: 6.7.1-arch1-1 x86_64 Up: 19m
Mem: 2.62/15.05 GiB (17.4%) Storage: 476.94 GiB (34.7% used) Procs: 412
Shell: Zsh inxi: 3.3.31
```

**Comment by raininja** [comment]
Ok, I issued "rustup update" and it built successfully!

**Comment by YaLTeR** [comment]
That's... an interesting error. Anyhow, pushed a fix to mark that enum as pub, should fix the build on 1.72.0.
